# Generated by Django 3.0.3 on 2020-06-17 03:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goesFire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav1Cords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='profile',
            name='fav2Cords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='profile',
            name='userCords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
